project:
  version: @project.version@

server:
  port: 8080
  servlet:
    context-path: /base-back-api
  error:
    include-message: always

spring:
  application.name: Base Back Api
#  security.user:
#    name: name
#    password: pass