project:
  version: @project.version@

server:
  port: 8080
  servlet:
    context-path: /kotlin-springboot-base
  error:
    include-message: always

spring:
  application.name: kotlin springBoot base
#  security.user:
#    name: name
#    password: pass

springdoc:
  api-docs:
    path: /api-docs